#!/usr/bin/awk -f

/^$/ || /^ [[:digit:]]/ {
    next
}

/^\[/ || /^ / {
    gsub(/[\[\]]/, "")
    gsub(/    /, "x")
    gsub(/ /, "")

    for(i = 1; i <= length($0); i++) {
        if(substr($0, i, 1) == "x") {
            continue
        } else {
            stack[i] = stack[i] substr($0, i, 1)
        }
    }
}

/^move/ {
    n = $2
    src = $4
    dst = $6

    for(i = 1; i <= n; i++) {
        c = substr(stack[src], 1, 1)
        stack[src] = substr(stack[src], 2)
        stack[dst] = c stack[dst]
    }
}

END {

    for(k in stack)
        part1 = part1 substr(stack[k], 1, 1)

    print "Part 1: " part1
}
