#!/usr/bin/perl

# use strict;
use warnings;

use List::Util qw(min max);

my @points;
while (<>) {
    /position=<(.*),(.*)> velocity=<(.*),(.*)>/;
    push @points, {
        x => $1,
        y => $2,
        dx => $3,
        dy => $4
    }
}

my $s = 0;
while () {
    # Only print the starfield if the stars are contained
    # in a box the height of a standard terminal window
    if (box_height (@points) <= 25) {
        print_msg (0, 2, @points);
        system "tput cup 0 0";
        print "Part 2: $s\n";
        sleep 1;
    }
    $s++;

    for my $p (@points) {
        $p = move_point ($p);
    }
}

endwin;

sub move_point {
    my $p = shift;

    return {
        x => $p->{'x'} + $p->{'dx'},
        y => $p->{'y'} + $p->{'dy'},
        dx => $p->{'dx'},
        dy => $p->{'dy'}
    };
}

sub print_msg {
    my $x = shift;
    my $y = shift;

    my ($min_x, $min_y) = get_bounds (@_);

    system "tput clear";
    for my $p (@points) {
        my $x = ($p->{'x'} - $min_x) + $x;
        my $y = ($p->{'y'} - $min_y) + $y;
        system "tput cup $y $x";
        print "#";
    }
}

sub box_height {
    my ($min_x, $min_y, $max_x, $max_y) = get_bounds (@_);

    return $max_y - $min_y;
}

sub get_bounds {
    my @points = @_;

    my $p = shift @points;
    my ($min_x, $min_y, $max_x, $max_y) = (
        $p->{'x'},
        $p->{'y'},
        $p->{'x'},
        $p->{'y'});

    for $p (@points) {
        $min_x = min ($min_x, $p->{'x'});        
        $min_y = min ($min_y, $p->{'y'});        
        $max_x = max ($max_x, $p->{'x'});        
        $max_y = max ($max_y, $p->{'y'});        
    }

    return ($min_x, $min_y, $max_x, $max_y);
}

