#!/bin/sh

n=0
a=
b=
c=
oldsum=

while read depth; do
    if [ -z "$depth" ]; then
        continue
    fi

    # Part 1: count number of increases
    test -z "$old" && old=$depth
    if [ "$depth" -gt "$old" ]; then
        n1=$((n1+1))
    fi
    old=$depth

    # Part 2: count number of increases in sliding window
    if [ -z "$a" ]; then
        a=$depth
        continue
    elif [ -z "$b" ]; then
        b=$depth
        continue
    elif [ -z "$c" ]; then
        c=$depth
    else
        a=$b
        b=$c
        c=$depth
    fi

    sum=$((a+b+c))
    test -z "$oldsum" && oldsum=$sum

    if [ "$sum" -gt "$oldsum" ]; then
        n2=$((n2+1))
    fi

    oldsum=$sum
done

printf "Part 1: %s\n" "$n1"
printf "Part 2: %s\n" "$n2"
