#!/bin/sh

n=0
while read depth; do
    test -z "$old" && old=$depth
    if [ "$depth" -gt "$old" ]; then
        echo "$depth increased"
        n=$((n+1))
    else
        echo "$depth decreased"
    fi
    old=$depth
done

echo $n
