#!/usr/bin/awk -f

/^forward/ { h += $2; d2 += aim * $2 }
/^reverse/ { h -= $2 }
/^up/      { d1 -= $2; aim -= $2 }
/^down/    { d1 += $2; aim += $2 }

END {
    printf("Part 1: %d\n", d1 * h)
    printf("Part 2: %d\n", d2 * h)
}
