#!/usr/bin/awk -f

function is_left(c) {
    return match(c, /[({[<]/)
}

function is_match(c1, c2) {
    if (c1 == "(" && c2 == ")") return 1
    if (c1 == "{" && c2 == "}") return 1
    if (c1 == "[" && c2 == "]") return 1
    if (c1 == "<" && c2 == ">") return 1
    return 0
}

BEGIN {

}

{ 
    sp = 0
    for (i = 1; i <= length($0); i++) {
        c = substr($0, i, 1)
        # Push left brackets
        if (is_left(c)) {
            stack[++sp] = c
        # Pop left bracket if we grabbed a matching close bracket
        } else if (is_match(stack[sp], c)) {
            sp--
        # Syntax error
        } else if (!is_match(stack[sp], c)) {
            corrupt = corrupt c
            break
        } else print "WTF?!"
    }
}

END {
    for (i = 1; i <= length(corrupt); i++) {
        c = substr(corrupt, i, 1)
             if (c == ")") score += 3
        else if (c == "}") score += 1197
        else if (c == "]") score += 57
        else if (c == ">") score += 25137
    }

    printf("Score: %s\n", score)
}
