#!/usr/bin/awk -f

{
    gsub(/[,-]/, " ")

    if(($1 >= $3 && $2 <= $4) || ($3 >= $1 && $4 <= $2))
        part1++

    if(($1 >= $3 && $1 <= $4) || ($3 >= $1 && $3 <= $2))
        part2++
}

END {
    print "Part 1: " part1
    print "Part 2: " part2
}
