#!/usr/bin/perl

# Split entries apart
while (<>) {
    ($yr, $mo, $dd, $hh, $mm, $log) = parse ($_);

    # Hash separate timestamp data and log entry
    push @entries, {
        'yr' => $yr,
        'mo' => $mo,
        'dd' => $dd,
        'hh' => $hh,
        'mm' => $mm,
        'log' => $log
    };
}

# Sort entries
@sorted_entries = sort {
    $a->{'yr'} <=> $b->{'yr'} ||
    $a->{'mo'} <=> $b->{'mo'} ||
    $a->{'dd'} <=> $b->{'dd'} ||
    $a->{'hh'} <=> $b->{'hh'} ||
    $a->{'mm'} <=> $b->{'mm'}
} @entries;

foreach (@sorted_entries) {
    $yr = $_->{'yr'};
    $mo = $_->{'mo'};
    $dd = $_->{'dd'};
    $hh = $_->{'hh'};
    $mm = $_->{'mm'};
    $log = $_->{'log'};

    # New guard on shift
    $guard = $1 if ($log =~ /Guard #(\d+) begins shift/);

    $dtg = "$yr$mo$dd";

    # Don't track unless during midnight hour
    next if ($hh ne "00");

    # Mark wake up/fall asleep times
    $guard_sched{$guard}{$dtg}[$mm] = 'wake' if ($log =~ /wakes up/);
    $guard_sched{$guard}{$dtg}[$mm] = 'sleep' if ($log =~ /falls asleep/);
}

$awake = 'yes';
foreach my $guard (sort keys %guard_sched) {
    foreach my $dtg (sort keys %{ $guard_sched{$guard} }) {
        for ($i = 0; $i < 60; $i++) {
            # Toggle sleep/wake
            if ($guard_sched{$guard}{$dtg}[$i] eq 'wake') {
                $awake = 'yes';
            } elsif ($guard_sched{$guard}{$dtg}[$i] eq 'sleep') {
                $awake = 'no';
            }

            # Save sleep/wake markers
            if ($awake eq 'no') {
                $guard_sched{$guard}{$dtg}[$i] = 1;
            } else {
                $guard_sched{$guard}{$dtg}[$i] = 0;
            }
        }
    }
}

# Sum guard asleep times
foreach my $guard (sort keys %guard_sched) {
    foreach my $dtg (sort keys %{ $guard_sched{$guard} }) {
        for ($i = 0; $i < 60; $i++) {
            if ($guard_sched{$guard}{$dtg}[$i] == 1) {
                $guard_awake_count{$guard} += 1;
                $min_totals{$guard}[$i] += 1;
            }
        }
    }
}
@guards = sort { $guard_awake_count{$a} <=> $guard_awake_count{$b} } keys %guard_awake_count;

for ($i = 0; $i < 60; $i++) {
    $test= $min_totals{$guards[-1]}[$i];
    if ($test > $max) {
        $max= $test;
        $result = $i
    }
}

print "Part 1: " . $guards[-1] * $result . "\n";

for ($i = 0; $i < 60; $i++) {
    foreach my $guard (keys %guard_sched) {
        next if (!$min_totals{$guard}[$i]);
        if ($min_totals{$guard}[$i] > $max_time) {
            $max_time = $min_totals{$guard}[$i];
            $max_min = $i;
            $high_guard = $guard;
        }
    }
}
print "Part 2: " . $high_guard * $max_min . "\n";

sub parse () {
    shift =~ /\[(....)\-(..)\-(..) (..):(..)\] (.*)/;
    return $1, $2, $3, $4, $5, $6
}

