#!/usr/bin/perl

use List::Util qw(min);

$polymer = <>;
chomp $polymer;

print "Part 1: " . reduce ($polymer) . "\n";

$short_len = length $polymer;
foreach my $c ('a'..'z'){
    $p = $polymer;

    $p =~ s/$c//g;
    $p =~ s/\U$c//g;

    $short_len = min ($short_len, reduce($p));
}
print "Part 2: $short_len\n";

sub reduce {
    my $polymer= shift;

    while (1) {
        my $change = 0;

        foreach my $c ('a'..'z'){
            my $C = uc $c;
            $change = 1 if($polymer =~ s/$c$C//g);
            $change = 1 if($polymer =~ s/$C$c//g);
        }
        last if($change == 0);
    }

    return length $polymer;
}

